import './modules/selects';
import './modules/hero-form-tabs';
import './modules/calendar-input';
import './modules/flights-sorting-tabs';
import './modules/hotels-sorting-tabs';
import './modules/tabs';
import './modules/filters-toggle';
import './modules/subnav';
import './modules/sliders';
